GENCCODE_ASSEMBLY_TYPE=-a gcc
SO=so
SOBJ=so
A=a
LIBPREFIX=lib
LIB_EXT_ORDER=.58.2
COMPILE=/home/conda/feedstock_root/build_artifacts/icu_1537667871488/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1 -DU_HAVE_STRTOD_L=1  -DU_ATTRIBUTE_DEPRECATED= -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/jupyter-bweill/final-project-fa2019-natty_daddies/geopandas/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/icu_1537667871488/work=/usr/local/src/conda/icu-58.2 -fdebug-prefix-map=/home/jupyter-bweill/final-project-fa2019-natty_daddies/geopandas=/usr/local/src/conda-prefix -std=c99 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -c
LIBFLAGS=-I/home/jupyter-bweill/final-project-fa2019-natty_daddies/geopandas/include -DPIC -fPIC
GENLIB=/home/conda/feedstock_root/build_artifacts/icu_1537667871488/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/jupyter-bweill/final-project-fa2019-natty_daddies/geopandas/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/icu_1537667871488/work=/usr/local/src/conda/icu-58.2 -fdebug-prefix-map=/home/jupyter-bweill/final-project-fa2019-natty_daddies/geopandas=/usr/local/src/conda-prefix -std=c99 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,-rpath,/home/jupyter-bweill/final-project-fa2019-natty_daddies/geopandas/lib -L/home/jupyter-bweill/final-project-fa2019-natty_daddies/geopandas/lib  -shared -Wl,-Bsymbolic
LDICUDTFLAGS=-nodefaultlibs -nostdlib
LD_SONAME=-Wl,-soname -Wl,
RPATH_FLAGS=
BIR_LDFLAGS=-Wl,-Bsymbolic
AR=/home/conda/feedstock_root/build_artifacts/icu_1537667871488/_build_env/bin/x86_64-conda_cos6-linux-gnu-ar
ARFLAGS=r
RANLIB=/home/conda/feedstock_root/build_artifacts/icu_1537667871488/_build_env/bin/x86_64-conda_cos6-linux-gnu-ranlib
INSTALL_CMD=/usr/bin/install -c
